Drop nix-community/cache-nix-action to fix direnv on GHA
I suspect this action causes below

```
direnv allow .
  direnv allow .
  direnv export gha > "$GITHUB_ENV"
  shell: /usr/bin/bash -e {0}
  env:
    NIX_PROFILES: /nix/var/nix/profiles/default /home/runner/.nix-profile
direnv: loading ~/work/nixpkgs-reviewing-workspace/nixpkgs-reviewing-workspace/.envrc
direnv: using flake
error: opening file '/nix/store/gz0r4gnai3bya1amslw5qwqlnpyld1gg-nix-shell.drv': No such file or directory
```